apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-parameters
  namespace: argo
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  kube_api_server_url: 'k8s://https://172.19.56.60:6443'