apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: etl-webhook
spec:
  service:
    ports:
      - port: 13000
        targetPort: 13000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    etl-webhook:
      # port to run HTTP server on
      port: "13000"
      # endpoint to listen to
      endpoint: /etl-webhook
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST

#    example-foo:
#      port: "12000"
#      endpoint: /example2
#      method: POST

# Uncomment to use secure webhook
#    example-secure:
#      port: "13000"
#      endpoint: "/secure"
#      method: "POST"
#      # k8s secret that contains the cert
#      serverCertSecret:
#        name: my-secret
#        key: cert-key
#      # k8s secret that contains the private key
#      serverKeySecret:
#        name: my-secret
#        key: pk-key